<a href="https://colab.research.google.com/github/M-Angeles/Linear-Algebra-58020/blob/main/Final_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Final Exam in Linear Algebra

Problem 1. Student A, Student B, and Student C have a total of Php 89 cash in their banks. Student A has 6 less than Student C.Student B has 3 times what Student C has. How much does each student have? (30 points)


In [29]:
import numpy as np
from scipy.linalg import solve
S = np.array([2,24,-8])
print(S)

inv_A = np.linalg.inv(A)
print(inv_A)


## the same error occurs as the correlation of  values are almost the same or near zero

[ 2 24 -8]


LinAlgError: ignored

Problem 2. Solve each system: (30 points)

3x - y + z = 5

9x - 3y +3z = 15

-12x +4y -4z = -20 


In [18]:
import numpy as np

A = np.array([[3,-1,1],[9,-3,3],[-12,4,-4]])
print(A)

B = np.array([[5],[15],[-20]])
print(B)

inv_A = np.linalg.inv(A)
print(inv_A)

## I think the error occurs as to when the values are the same for the matrix 
## if or when the linear equation has been computed into their lowest terms as you can see if 
## the second and third row will be computed into their lowest term what will come out is
## for the second row = 3,-1,1  and for the third -3,1,-1 which is when transformed is also the same 
## as the 1st row hence all of them has the same values.

[[  3  -1   1]
 [  9  -3   3]
 [-12   4  -4]]
[[  5]
 [ 15]
 [-20]]


LinAlgError: ignored

Problem 3. Find the eigenvalue/s
           Find the eigenvectors

In [13]:
import numpy as np
from numpy.linalg import eig
A = np.array([[-8,5,-6],[-12,-9,12],[-3,-3,5]])
print(A)

w,v = np.linalg.eig(A)
print("The eigenvalue/s is/are",w)
print("The right eigenvectors are",v)

[[ -8   5  -6]
 [-12  -9  12]
 [ -3  -3   5]]
The eigenvalue/s is/are [-6.79632288+6.36068117j -6.79632288-6.36068117j  1.59264577+0.j        ]
The right eigenvectors are [[ 0.07327305-0.44517511j  0.07327305+0.44517511j -0.01438062+0.j        ]
 [ 0.86180431+0.j          0.86180431-0.j          0.75671476+0.j        ]
 [ 0.23153459+0.0116301j   0.23153459-0.0116301j   0.653587  +0.j        ]]
