<a href="https://colab.research.google.com/github/M-Angeles/Linear-Algebra-58020/blob/main/Matrix_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Python program to Inverse


In [40]:
import numpy as np 
## inverse of 3x3 matrix
A = np.array([[10, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
print(A)

[[10  2  3]
 [ 4  5  6]
 [ 7  8  9]]


In [43]:
B = np.linalg.inv(A)

print(B)

[[ 0.11111111 -0.22222222  0.11111111]
 [-0.22222222 -2.55555556  1.77777778]
 [ 0.11111111  2.44444444 -1.55555556]]


In [42]:
print(np.dot(A,B))

[[ 1.00000000e+00  0.00000000e+00 -2.22044605e-16]
 [-2.77555756e-17  1.00000000e+00  1.33226763e-15]
 [ 6.93889390e-17 -2.66453526e-15  1.00000000e+00]]


In [50]:
## inverse of 4x4 matrix
AB = np.array([[10, 20, 30, 15],
               [40, 50, 60, 25],
               [70, 80, 90, 35],
               [45, 55, 65, 75]])
print(AB)

[[10 20 30 15]
 [40 50 60 25]
 [70 80 90 35]
 [45 55 65 75]]


In [51]:
print(np.linalg.inv(AB))

[[ 7.03687442e+13 -1.40737488e+14  7.03687442e+13 -2.43186512e-03]
 [-1.40737488e+14  2.81474977e+14 -1.40737488e+14  1.52085578e-02]
 [ 7.03687442e+13 -1.40737488e+14  7.03687442e+13 -1.96732444e-02]
 [ 1.20689655e-02 -4.13793103e-02  8.62068966e-03  2.06896552e-02]]


##Python Program to Transpose

In [44]:
## transpose of a 3x3 matrix
A = np.array([[10, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
print(A)

[[10  2  3]
 [ 4  5  6]
 [ 7  8  9]]


In [45]:
C = np.transpose(A)
print(C)

[[10  4  7]
 [ 2  5  8]
 [ 3  6  9]]


In [52]:
## transpose of 4x4 matrix
AB = np.array([[10, 20, 30, 15],
               [40, 50, 60, 25],
               [70, 80, 90, 35],
               [45, 55, 65, 75]])
print(AB)

[[10 20 30 15]
 [40 50 60 25]
 [70 80 90 35]
 [45 55 65 75]]


In [53]:
print(np.transpose(AB))

[[10 40 70 45]
 [20 50 80 55]
 [30 60 90 65]
 [15 25 35 75]]
