<a href="https://colab.research.google.com/github/M-Angeles/Linear-Algebra-58020/blob/main/Midterm_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Midterm Exam

In [20]:
import numpy as np

##Question 1. Create a Python code that displays a square matrix whose length is 5 (10 points)

A = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [19]:
##Question 2. Create a Python code that displays a square matrix whose elements below the principal diagonal are zero (10 points)

B = np.array([[1,2,3],[0,4,5],[0,0,6]])
print(B)

[[1 2 3]
 [0 4 5]
 [0 0 6]]


In [18]:
##Question 3. Create a Python code that displays a square matrix which is symmetrical (10 points)
C = np.array([[1,2,3],[2,2,3],[3,3,1]])
print(C)

[[1 2 3]
 [2 2 3]
 [3 3 1]]


In [17]:
##Question 4. What is the inverse of matrix C? Show your solution by python coding. (20 points)

D = np.array([[1,2,3],[2,3,3],[3,4,-2]])
print(D)

inv_D = np.linalg.inv(D)
print(inv_D)

[[ 1  2  3]
 [ 2  3  3]
 [ 3  4 -2]]
[[-3.6  3.2 -0.6]
 [ 2.6 -2.2  0.6]
 [-0.2  0.4 -0.2]]


In [16]:
##Question 5. What is the determinant of the given matrix in Question 4? Show your solution by python coding. (20 points)

E = np.array([[1,2,3],[2,3,3],[3,4,-2]])
print(E)

print(np.linalg.det(E))
print(round(np.linalg.det(E)))



[[ 1  2  3]
 [ 2  3  3]
 [ 3  4 -2]]
5.000000000000001
5


In [15]:
##Question 6. Find the roots of the linear equations by showing its python codes (30 points)

##5X1 + 4X2 + X3 = 3.4

##10X1 + 9X2 + 4X3 = 8.8

##10X1 + 13X2 + 15X3 = 19.2

F = np.array([[5,4,1],[10,9,4],[10,13,15]])
print(E)

inv_F = np.linalg.inv(F)
print(inv_F)

G = np.array([[3.4],[8.8],[19.2]])
print(G)

X = np.dot(inv_F,G)
print(X)



[[ 5  4  1]
 [10  9  4]
 [10 13 15]]
[[ 5.53333333 -3.13333333  0.46666667]
 [-7.33333333  4.33333333 -0.66666667]
 [ 2.66666667 -1.66666667  0.33333333]]
[[ 3.4]
 [ 8.8]
 [19.2]]
[[0.2]
 [0.4]
 [0.8]]
