<a href="https://colab.research.google.com/github/M-Angeles/Linear-Algebra-58020/blob/main/Practical_Lab_Exam_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Practical Lab Exam 1
  

In [7]:
import numpy as np

W = np.array([[1,-3],[2,-2],[3,1]])
X = np.array([[3,2,1],[-1,2,3],[2,-1,1]])
Y = np.array([[1,2,0],[0,-1,2]])
Z = np.array([[0,1],[2,3]])
print(W)
print(X)
print(Y)
print(Z)

[[ 1 -3]
 [ 2 -2]
 [ 3  1]]
[[ 3  2  1]
 [-1  2  3]
 [ 2 -1  1]]
[[ 1  2  0]
 [ 0 -1  2]]
[[0 1]
 [2 3]]


####Problem 1

In [14]:
##a. WY
W = np.array([[1,-3],[2,-2],[3,1]])
Y = np.array([[1,2,0],[0,-1,2]])

P = np.dot(W,Y)

print(P)


[[ 1  5 -6]
 [ 2  6 -4]
 [ 3  5  2]]


In [11]:
##b. Z+Z
Z = np.array([[0,1],[2,3]])

R = Z+Z
print(R)

[[0 2]
 [4 6]]


In [12]:
##c. 3X
X = np.array([[3,2,1],[-1,2,3],[2,-1,1]])

A = np.multiply(3,X)
print(A)

[[ 9  6  3]
 [-3  6  9]
 [ 6 -3  3]]


##Problem 2


In [27]:
##The product (YW)^2 is not defined
W = np.array([[1,-3],[2,-2],[3,1]])
Y = np.array([[1,2,0],[0,-1,2]])

P = np.dot(Y,W)

Q = np.multiply(P,P)
print(Q)
##The answer is false

[[25 49]
 [16 16]]


In [18]:
##b. WY – X = 
X = np.array([[3,2,1],[-1,2,3],[2,-1,1]])

B = np.subtract(P,X)
print(B)
##The answer is true

[[-2  3 -7]
 [ 3  4 -7]
 [ 1  6  1]]


In [21]:
##c. YW – Z2 =
W = np.array([[1,-3],[2,-2],[3,1]])
Y = np.array([[1,2,0],[0,-1,2]])

C =np.dot(Y,W)
print(C)

[[ 5 -7]
 [ 4  4]]


In [26]:
Z = np.array([[0,1],[2,3]])
D = np.multiply(Z,Z)

print(D)

[[0 1]
 [4 9]]


In [29]:
Result = np.subtract(C,D)
print(Result)

##The answer is false

[[ 5 -8]
 [ 0 -5]]


###The only statement that is true is letter b.