<a href="https://colab.research.google.com/github/M-Angeles/Linear-Algebra-58020/blob/main/Prelim_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Prelim Exam


In [8]:
import numpy as np

##Question 1

C = np.array([1,1,1,1])

print(np.diag(C))

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [10]:
##Question 2
C = np.array([1,1,1,1])

A = np.diag(C)

print(np.multiply(A,A))

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [5]:
##Question 3

A = np.array([2,7,4])
B = np.array([3,9,8])

print(np.cross(A,B))

[20 -4 -3]
