<a href="https://colab.research.google.com/github/M-Angeles/Linear-Algebra-58020/blob/main/Python_Exercise_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Matrix and its Operations

In [2]:
import numpy as np

A = np.array([[-5,0],[4,1]])
print(A)

[[-5  0]
 [ 4  1]]


In [3]:
B = np.array([[6,-3],[2,3]])
print(B)

[[ 6 -3]
 [ 2  3]]


In [4]:
#sum = A+B
A = np.array([[-5,0],[4,1]])
B = np.array([[6,-3],[2,3]])
print(A+B)

[[ 1 -3]
 [ 6  4]]


In [5]:
#difference1 = A - B
A = np.array([[-5,0],[4,1]])
B = np.array([[6,-3],[2,3]])
print(A-B)

[[-11   3]
 [  2  -2]]


In [6]:
#difference2 = B - B
B = np.array([[6,-3],[2,3]])
print(B-B)

[[0 0]
 [0 0]]
