<a href="https://colab.research.google.com/github/M-Angeles/Linear-Algebra-58020/blob/main/Vector_representation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Matrix and its Operations


In [ ]:
import numpy as np
#Create an 1x3 matrix

x = np.array([1,2,3])
print(x)


[1 2 3]


In [ ]:
#Create a 2x3 matrix

y = np.array([[1,2,3],[4,5,6]])

print(y)

[[1 2 3]
 [4 5 6]]


In [ ]:
#Create a 3x3 matrix
z = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(z)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [31]:
#Create a constant with all values are 6

a = np.array([[6,6],[6,6]])
print(a)

a = np.full((2,2),6)
print(a)

[[6 6]
 [6 6]]
[[6 6]
 [6 6]]


In [15]:
#Create a diagonal matrix
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)
c = np.diagonal([[1,2,3],[4,5,6],[7,8,9]])
print(c)

[1 5 9]


In [11]:
#Create an identity matrix
q = np.eye(4)

print(q)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [14]:
#Create a zero matrix
w = np.zeros((4,5))
print(w)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [16]:
#Create an empty matrix

e = np.empty((0,5))
print(e)

[]


In [20]:
#Addition of matrices
r = np.array([[1,2,3],[4,5,6]])
t = np.zeros((2,3))

print (r+t)


[[1. 2. 3.]
 [4. 5. 6.]]


In [24]:
#Subtraction of Matrices

r = np.array([[1,2,3],[4,5,6]])
t = np.array([[-1,2,4],[7,4,2]])
#print(r)
#print(t)
print (r-t)

[[1 2 3]
 [4 5 6]]
[[-1  2  4]
 [ 7  4  2]]
[[ 2  0 -1]
 [-3  1  4]]
